# Generated by Django 5.2.17 on 2026-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
