# Generated by Django 5.2.17 on 2026-09-13 11:43

import accounts.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recruiter_profile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.recruiter_photo_path, validators=[core.validators.validate_image]),
        ),
    ]
