# Generated by Django 5.2.17 on 2026-09-06 17:29

import applications.models
import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, upload_to=applications.models.application_resume_path, validators=[core.validators.validate_pdf])),
                ('resume_source', models.CharField(choices=[('none', 'None'), ('profile', 'Profile resume'), ('upload', 'Uploaded resume')], default='none', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('job', 'student'), name='one_application_per_student_job')],
            },
        ),
    ]
