# Generated by Django 5.2.17 on 2026-09-06 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Remote', 'Remote')], max_length=30)),
                ('industry', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Engineering', 'Engineering'), ('Business', 'Business'), ('Design', 'Design')], max_length=60)),
                ('description', models.TextField()),
                ('compensation_min', models.PositiveBigIntegerField()),
                ('compensation_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resume_required', models.BooleanField(default=True)),
                ('cover_letter_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.recruiterprofile')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='accounts.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
