# Generated by Django 5.2.17 on 2026-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('Computer Science', 'Computer Science')], max_length=60),
        ),
    ]
